### PR TITLE
Fixes prefix and suffix text issue

### LINKED ISSUE #5: Prefix text is not taken into textfield width
When some `prefixText` is added, textfield area is smaller by the width of prefixText data. In the below example, the textfield is 1 character smaller (because of the dollar symbol prefix text).

```dart
    AutoSizeTextField(
      fullwidth: false,
      controller: _priceController,
      onChanged: _cubit.priceChanged,
      keyboardType: TextInputType.number,
      decoration: InputDecoration(
        prefixText: '\$',
        contentPadding: EdgeInsets.zero,
      ),
    )
```

### PR DESCRIPTION
**Pull request by excogitatr**
Closes #5

### CODE REVIEW

File: lib/src/auto_size_text_field.dart [hunk 1]
```diff
@@ -718,6 +716,12 @@ class _AutoSizeTextFieldState extends State<AutoSizeTextField> {
     if (!widget.wrapWords) {
       var words = text.toPlainText().split(RegExp('\\s+'));
 
+      // Adds prefix and suffix text
+      if (widget.decoration.prefixText != null)
+        words.add(widget.decoration.prefixText);
+      if (widget.decoration.suffixText != null)
+        words.add(widget.decoration.suffixText);
```
Comment (lzhuor) [inline lib/src/auto_size_text_field.dart:723]: Hi @excogitatr This code change assumes that the `hintText` always shares the same textStyle as the input text which might not always be the case. We should consider the size of `hintText` with `hintStyle`. 

What do you think?

File: example/ios/Flutter/.last_build_id [hunk 2]
```diff
@@ -0,0 +1 @@
+88660c30393714dd14b96d2d4997a735
```
Comment (lzhuor) [inline example/ios/Flutter/.last_build_id:1]: This file should not be comitted.

**Review by lzhuor — COMMENTED** [review]
Thanks for PR @excogitatr . Left some questions and comments.

File: lib/src/auto_size_text_field.dart (hunk 1 above)
Comment (excogitatr) [reply lib/src/auto_size_text_field.dart:723]: Makes sense. Then should there be a seperate text painter and it will be added directly to `_textSpanWidth`?

Comment (lzhuor) [reply lib/src/auto_size_text_field.dart:723]: Absolutely. 👍

Comment (excogitatr) [reply lib/src/auto_size_text_field.dart:723]: BTW @lzhuor  I just realized that, prefix and suffix text is always same as the input text. It is completely different from hint. So, I don't think there will be any issue with this code.

Comment (lzhuor) [reply lib/src/auto_size_text_field.dart:723]: Gotcha. Good catch.

**Review by lzhuor — APPROVED** [review]
LGTM

**Comment by lzhuor** [comment]
🚀 LGTM and merged. Great stuff. Thank you @excogitatr

**Comment by lzhuor** [comment]
@excogitatr Published as part of 0.1.7 https://pub.dev/packages/auto_size_text_field

I reverted your change of `pubspec.lock` to support older Flutter SDKs and Dart SDKs also fixed the example of prefix and suffix. You can refer to this PR #8 

Please note that prefix and suffix could have different `textStyle`, so your assumption isn't completely correct. Will need to address it in the future.

https://api.flutter.dev/flutter/material/InputDecoration/suffixStyle.html
https://api.flutter.dev/flutter/material/InputDecoration/prefixStyle.html

Thank you!
